name: Build Solution

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2022 # change to ubuntu-latest if borked

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.7.2'  # Use the desired version

    - name: Restore Dependencies
      run: dotnet restore CustomMenuText.sln

    - name: Build Solution
      run: dotnet build CustomMenuText.sln --configuration Release

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CustomMenuText
        path: path/to/CustomMenuText.dll

  AutoRelease:
    runs-on: windows-2022
    needs: build
    steps:
    - name: Download Release Artifact
      uses: actions/download-artifact@v2
      with:
        name: CustomMenuText

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      id: automatic_releases
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: CustomMenuText.dll
